/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

#include "IntegerType.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 91 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MiniCBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_INT = 5,                      /* T_INT  */
  YYSYMBOL_T_RETURN = 6,                   /* T_RETURN  */
  YYSYMBOL_T_IF = 7,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 8,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 9,                    /* T_WHILE  */
  YYSYMBOL_T_BREAK = 10,                   /* T_BREAK  */
  YYSYMBOL_T_CONTINUE = 11,                /* T_CONTINUE  */
  YYSYMBOL_T_SEMICOLON = 12,               /* T_SEMICOLON  */
  YYSYMBOL_T_L_PAREN = 13,                 /* T_L_PAREN  */
  YYSYMBOL_T_R_PAREN = 14,                 /* T_R_PAREN  */
  YYSYMBOL_T_L_BRACE = 15,                 /* T_L_BRACE  */
  YYSYMBOL_T_R_BRACE = 16,                 /* T_R_BRACE  */
  YYSYMBOL_T_L_SQUARE = 17,                /* T_L_SQUARE  */
  YYSYMBOL_T_R_SQUARE = 18,                /* T_R_SQUARE  */
  YYSYMBOL_T_COMMA = 19,                   /* T_COMMA  */
  YYSYMBOL_T_CONST = 20,                   /* T_CONST  */
  YYSYMBOL_T_ASSIGN = 21,                  /* T_ASSIGN  */
  YYSYMBOL_T_SUB = 22,                     /* T_SUB  */
  YYSYMBOL_T_ADD = 23,                     /* T_ADD  */
  YYSYMBOL_T_MUL = 24,                     /* T_MUL  */
  YYSYMBOL_T_DIV = 25,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 26,                     /* T_MOD  */
  YYSYMBOL_T_LT = 27,                      /* T_LT  */
  YYSYMBOL_T_LE = 28,                      /* T_LE  */
  YYSYMBOL_T_GT = 29,                      /* T_GT  */
  YYSYMBOL_T_GE = 30,                      /* T_GE  */
  YYSYMBOL_T_EQ = 31,                      /* T_EQ  */
  YYSYMBOL_T_NEQ = 32,                     /* T_NEQ  */
  YYSYMBOL_T_AND = 33,                     /* T_AND  */
  YYSYMBOL_T_OR = 34,                      /* T_OR  */
  YYSYMBOL_T_NOT = 35,                     /* T_NOT  */
  YYSYMBOL_T_FLOAT_LITERAL = 36,           /* T_FLOAT_LITERAL  */
  YYSYMBOL_T_FLOAT = 37,                   /* T_FLOAT  */
  YYSYMBOL_YYACCEPT = 38,                  /* $accept  */
  YYSYMBOL_CompileUnit = 39,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 40,                   /* FuncDef  */
  YYSYMBOL_FormalParamList = 41,           /* FormalParamList  */
  YYSYMBOL_FormalParam = 42,               /* FormalParam  */
  YYSYMBOL_FuncFParamArrayDim = 43,        /* FuncFParamArrayDim  */
  YYSYMBOL_Block = 44,                     /* Block  */
  YYSYMBOL_BlockItemList = 45,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 46,                 /* BlockItem  */
  YYSYMBOL_VarDecl = 47,                   /* VarDecl  */
  YYSYMBOL_VarDeclExpr = 48,               /* VarDeclExpr  */
  YYSYMBOL_VarDef = 49,                    /* VarDef  */
  YYSYMBOL_ArrayDim = 50,                  /* ArrayDim  */
  YYSYMBOL_ConstExp = 51,                  /* ConstExp  */
  YYSYMBOL_InitVal = 52,                   /* InitVal  */
  YYSYMBOL_InitValList = 53,               /* InitValList  */
  YYSYMBOL_ConstDecl = 54,                 /* ConstDecl  */
  YYSYMBOL_ConstDefList = 55,              /* ConstDefList  */
  YYSYMBOL_ConstDef = 56,                  /* ConstDef  */
  YYSYMBOL_ConstInitVal = 57,              /* ConstInitVal  */
  YYSYMBOL_ConstInitValList = 58,          /* ConstInitValList  */
  YYSYMBOL_BasicType = 59,                 /* BasicType  */
  YYSYMBOL_Statement = 60,                 /* Statement  */
  YYSYMBOL_IFStmt = 61,                    /* IFStmt  */
  YYSYMBOL_Expr = 62,                      /* Expr  */
  YYSYMBOL_AddExp = 63,                    /* AddExp  */
  YYSYMBOL_MulExp = 64,                    /* MulExp  */
  YYSYMBOL_RelExp = 65,                    /* RelExp  */
  YYSYMBOL_EqExp = 66,                     /* EqExp  */
  YYSYMBOL_LAndExp = 67,                   /* LAndExp  */
  YYSYMBOL_LOrExp = 68,                    /* LOrExp  */
  YYSYMBOL_AddOp = 69,                     /* AddOp  */
  YYSYMBOL_MulOp = 70,                     /* MulOp  */
  YYSYMBOL_RelOp = 71,                     /* RelOp  */
  YYSYMBOL_EqOp = 72,                      /* EqOp  */
  YYSYMBOL_Cond = 73,                      /* Cond  */
  YYSYMBOL_UnaryExp = 74,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 75,                /* PrimaryExp  */
  YYSYMBOL_RealParamList = 76,             /* RealParamList  */
  YYSYMBOL_LVal = 77                       /* LVal  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  11
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   282

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  38
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  40
/* YYNRULES -- Number of rules.  */
#define YYNRULES  106
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  181

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   292


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36,    37
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,   103,   103,   107,   111,   115,   119,   123,   132,   139,
     149,   152,   158,   165,   176,   180,   184,   200,   206,   217,
     222,   232,   235,   238,   249,   256,   267,   276,   280,   285,
     290,   302,   305,   311,   314,   323,   327,   331,   338,   341,
     347,   354,   357,   363,   368,   381,   384,   387,   393,   396,
     406,   409,   420,   423,   426,   429,   432,   435,   438,   441,
     444,   451,   454,   457,   465,   468,   478,   481,   484,   493,
     496,   499,   505,   508,   511,   517,   520,   523,   529,   532,
     538,   541,   547,   550,   556,   557,   558,   562,   563,   564,
     565,   569,   570,   573,   583,   586,   589,   592,   599,   610,
     614,   620,   626,   635,   639,   647,   651
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_INT", "T_RETURN", "T_IF", "T_ELSE", "T_WHILE", "T_BREAK",
  "T_CONTINUE", "T_SEMICOLON", "T_L_PAREN", "T_R_PAREN", "T_L_BRACE",
  "T_R_BRACE", "T_L_SQUARE", "T_R_SQUARE", "T_COMMA", "T_CONST",
  "T_ASSIGN", "T_SUB", "T_ADD", "T_MUL", "T_DIV", "T_MOD", "T_LT", "T_LE",
  "T_GT", "T_GE", "T_EQ", "T_NEQ", "T_AND", "T_OR", "T_NOT",
  "T_FLOAT_LITERAL", "T_FLOAT", "$accept", "CompileUnit", "FuncDef",
  "FormalParamList", "FormalParam", "FuncFParamArrayDim", "Block",
  "BlockItemList", "BlockItem", "VarDecl", "VarDeclExpr", "VarDef",
  "ArrayDim", "ConstExp", "InitVal", "InitValList", "ConstDecl",
  "ConstDefList", "ConstDef", "ConstInitVal", "ConstInitValList",
  "BasicType", "Statement", "IFStmt", "Expr", "AddExp", "MulExp", "RelExp",
  "EqExp", "LAndExp", "LOrExp", "AddOp", "MulOp", "RelOp", "EqOp", "Cond",
  "UnaryExp", "PrimaryExp", "RealParamList", "LVal", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-67)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-65)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
      10,   -67,    12,   -67,     9,   -67,   -67,    19,   -67,     7,
      17,   -67,   -67,   -67,   -67,   -67,    56,    20,   -67,    49,
      40,   -67,    84,   -67,    11,    95,   198,   131,   222,   145,
     -67,    17,    25,    36,   -67,    63,   141,    66,   129,   164,
     164,   -67,    35,    99,   170,   197,   -67,    69,     8,    41,
     -67,   -67,    97,   211,   221,    62,    70,    95,   198,   194,
     -67,   -67,   222,   -67,   134,   -67,    25,    12,   144,    61,
     102,   -67,   -67,   -67,   -67,   -67,   -67,   164,   -67,   -67,
     -67,   164,   164,   164,   129,   -67,   -67,   139,   -67,   -67,
     -67,   -67,   164,   -67,   -67,   164,   164,   164,   164,   164,
     110,   -67,   -67,   -67,   235,   -67,   129,   150,   175,   178,
     191,   -67,   -67,   -67,   169,   -67,   -67,   -67,    56,   -67,
     -67,   202,   166,   -67,   -67,   214,   244,   -67,   -67,    59,
     -67,   197,   197,   -67,   -67,   213,   -67,   198,    99,    99,
     218,   218,   221,    62,   -67,   -67,   222,   250,   164,   164,
     -67,   -67,   -67,   -67,   -67,   129,   -67,   245,    95,   -67,
     129,   -67,   -67,   -67,   -67,    70,   251,   252,   255,   -67,
     246,   -67,    78,    78,   -67,   -67,   260,   -67,    78,   -67,
     -67
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    50,     0,    51,     0,     2,     3,     0,     4,     0,
       0,     1,     5,     6,     7,    24,     0,    27,    25,     0,
       0,    41,    27,    26,     0,     0,     0,    28,     0,     0,
      40,     0,     0,     0,    10,     0,   100,   105,     0,     0,
       0,   102,     0,    34,    66,    69,    94,   101,   100,     0,
      29,    35,    72,    75,    78,    80,    65,     0,     0,     0,
      45,    43,     0,    42,     0,     8,     0,     0,    12,     0,
       0,   100,    95,    96,    31,    83,    82,     0,    84,    85,
      86,     0,     0,     0,     0,    36,    38,     0,    87,    88,
      89,    90,     0,    91,    92,     0,     0,     0,     0,     0,
       0,    30,    46,    48,     0,    44,     0,     0,     0,     0,
       0,    57,    17,    55,     0,    19,    22,    23,     0,    21,
      52,     0,   101,     9,    11,     0,    13,    97,   103,     0,
      99,    68,    67,    71,    70,     0,    37,     0,    73,    74,
      76,    77,    79,    81,    32,    47,     0,     0,     0,     0,
      59,    60,    18,    20,    56,     0,    14,     0,     0,    98,
       0,   106,    39,    49,    53,    93,     0,     0,     0,    15,
       0,   104,     0,     0,    54,    16,    61,    58,     0,    63,
      52
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
     -67,   -67,   265,   -67,   203,   -67,   -24,   -67,   157,   208,
     -67,   256,   254,   -22,   -45,   -67,   215,   -67,   243,   -52,
     -67,     4,   -66,    98,   -26,   -23,   147,   159,   177,   179,
     111,   233,   234,   228,   229,   132,   -21,   -67,   -67,   -63
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_uint8 yydefgoto[] =
{
       0,     4,     5,    33,    34,   126,   113,   114,   115,   116,
       7,    18,    27,    60,    50,    87,   117,    20,    21,    61,
     104,     9,   119,   120,   121,    52,    44,    53,    54,    55,
      56,    77,    82,    95,    97,   166,    45,    46,   129,    47
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_int16 yytable[] =
{
      51,   122,    43,    42,    86,    43,    10,   103,    65,    11,
     105,    17,    70,   101,     1,     1,     1,     1,    72,    73,
     -64,    19,   -64,    51,   -64,    32,   -64,   -64,    35,     2,
       2,    15,    51,    24,    43,   100,    43,    25,    16,    43,
      64,    26,   123,   128,    48,    37,     3,     3,     3,     3,
      66,   122,    30,    74,    38,    67,    49,    85,   135,    31,
      22,   133,   134,    39,    48,    37,    25,    68,   118,   138,
      28,    35,   139,   159,    38,   127,    40,    41,   160,    69,
     147,    48,    37,    39,   106,   107,    84,   108,   109,   110,
     111,    38,   162,    64,   163,    98,    40,    41,    36,    37,
      39,    25,    43,   157,    99,    26,   176,   177,    38,   122,
     122,    51,   179,    40,    41,   122,   130,    39,   118,    75,
      76,    75,    76,    43,    88,    89,    90,    91,   144,   168,
      40,    41,    48,    37,   171,    43,   170,    48,    37,     1,
     106,   107,    38,   108,   109,   110,   111,    38,    57,    64,
     112,    39,    58,   -33,     2,   136,    39,   -33,   137,   -33,
     -33,   125,    57,   148,    40,    41,    62,    71,    37,    40,
      41,     3,    48,    37,     1,   106,   107,    38,   108,   109,
     110,   111,    38,    84,    64,   152,    39,   155,   149,     2,
     150,    39,    75,    76,    78,    79,    80,    36,    37,    40,
      41,    48,    37,   151,    40,    41,     3,    38,     6,    59,
     102,    38,    13,    49,   154,     8,    39,    36,    37,    14,
      39,    78,    79,    80,   131,    36,    37,    38,   132,    40,
      41,   161,   156,    40,    41,    38,    39,    59,    88,    89,
      90,    91,    93,    94,    39,    88,    89,    90,    91,    40,
      41,   145,    93,    94,   146,   140,   141,    40,    41,   165,
     165,   158,   164,   169,   175,   172,   173,   174,   178,    12,
     124,   153,    23,    29,    63,   142,   180,    81,   143,    83,
      92,   167,    96
};

static const yytype_uint8 yycheck[] =
{
      26,    64,    25,    25,    49,    28,     2,    59,    32,     0,
      62,     4,    38,    58,     5,     5,     5,     5,    39,    40,
      12,     4,    14,    49,    16,    14,    18,    19,    24,    20,
      20,    12,    58,    13,    57,    57,    59,    17,    19,    62,
      15,    21,    66,    69,     3,     4,    37,    37,    37,    37,
      14,   114,    12,    18,    13,    19,    15,    16,    84,    19,
       4,    82,    83,    22,     3,     4,    17,     4,    64,    92,
      21,    67,    95,    14,    13,    14,    35,    36,    19,    13,
     106,     3,     4,    22,     6,     7,    17,     9,    10,    11,
      12,    13,   137,    15,   146,    33,    35,    36,     3,     4,
      22,    17,   125,   125,    34,    21,   172,   173,    13,   172,
     173,   137,   178,    35,    36,   178,    14,    22,   114,    22,
      23,    22,    23,   146,    27,    28,    29,    30,    18,   155,
      35,    36,     3,     4,   160,   158,   158,     3,     4,     5,
       6,     7,    13,     9,    10,    11,    12,    13,    17,    15,
      16,    22,    21,    12,    20,    16,    22,    16,    19,    18,
      19,    17,    17,    13,    35,    36,    21,     3,     4,    35,
      36,    37,     3,     4,     5,     6,     7,    13,     9,    10,
      11,    12,    13,    17,    15,    16,    22,    21,    13,    20,
      12,    22,    22,    23,    24,    25,    26,     3,     4,    35,
      36,     3,     4,    12,    35,    36,    37,    13,     0,    15,
      16,    13,     4,    15,    12,     0,    22,     3,     4,     4,
      22,    24,    25,    26,    77,     3,     4,    13,    81,    35,
      36,    18,    18,    35,    36,    13,    22,    15,    27,    28,
      29,    30,    31,    32,    22,    27,    28,    29,    30,    35,
      36,    16,    31,    32,    19,    96,    97,    35,    36,   148,
     149,    17,    12,    18,    18,    14,    14,    12,     8,     4,
      67,   114,    16,    19,    31,    98,   178,    44,    99,    45,
      52,   149,    53
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     5,    20,    37,    39,    40,    47,    48,    54,    59,
      59,     0,    40,    47,    54,    12,    19,     4,    49,     4,
      55,    56,     4,    49,    13,    17,    21,    50,    21,    50,
      12,    19,    14,    41,    42,    59,     3,     4,    13,    22,
      35,    36,    51,    63,    64,    74,    75,    77,     3,    15,
      52,    62,    63,    65,    66,    67,    68,    17,    21,    15,
      51,    57,    21,    56,    15,    44,    14,    19,     4,    13,
      62,     3,    74,    74,    18,    22,    23,    69,    24,    25,
      26,    69,    70,    70,    17,    16,    52,    53,    27,    28,
      29,    30,    71,    31,    32,    71,    72,    72,    33,    34,
      51,    52,    16,    57,    58,    57,     6,     7,     9,    10,
      11,    12,    16,    44,    45,    46,    47,    54,    59,    60,
      61,    62,    77,    44,    42,    17,    43,    14,    62,    76,
      14,    64,    64,    74,    74,    62,    16,    19,    63,    63,
      65,    65,    66,    67,    18,    16,    19,    62,    13,    13,
      12,    12,    16,    46,    12,    21,    18,    51,    17,    14,
      19,    18,    52,    57,    12,    68,    73,    73,    62,    18,
      51,    62,    14,    14,    12,    18,    60,    60,     8,    60,
      61
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    38,    39,    39,    39,    39,    39,    39,    40,    40,
      41,    41,    42,    42,    43,    43,    43,    44,    44,    45,
      45,    46,    46,    46,    47,    48,    48,    49,    49,    49,
      49,    50,    50,    51,    51,    52,    52,    52,    53,    53,
      54,    55,    55,    56,    56,    57,    57,    57,    58,    58,
      59,    59,    60,    60,    60,    60,    60,    60,    60,    60,
      60,    61,    61,    61,    62,    62,    63,    63,    63,    64,
      64,    64,    65,    65,    65,    66,    66,    66,    67,    67,
      68,    68,    69,    69,    70,    70,    70,    71,    71,    71,
      71,    72,    72,    73,    74,    74,    74,    74,    74,    75,
      75,    75,    75,    76,    76,    77,    77
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     1,     2,     2,     2,     5,     6,
       1,     3,     2,     3,     2,     3,     4,     2,     3,     1,
       2,     1,     1,     1,     2,     2,     3,     1,     2,     3,
       4,     3,     4,     1,     1,     1,     2,     3,     1,     3,
       4,     1,     3,     3,     4,     1,     2,     3,     1,     3,
       1,     1,     1,     3,     4,     1,     2,     1,     5,     2,
       2,     5,     7,     7,     1,     1,     1,     3,     3,     1,
       3,     3,     1,     3,     3,     1,     3,     3,     1,     3,
       1,     3,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     1,     1,     1,     2,     2,     3,     4,     3,
       1,     1,     1,     1,     3,     1,     4
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 103 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        if (ast_root == nullptr) ast_root = (yyval.node);
    }
#line 1306 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 3: /* CompileUnit: VarDecl  */
#line 107 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        if (ast_root == nullptr) ast_root = (yyval.node);
    }
#line 1315 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 4: /* CompileUnit: ConstDecl  */
#line 111 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        if (ast_root == nullptr) ast_root = (yyval.node);
    }
#line 1324 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit FuncDef  */
#line 115 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
        // 这里不要改ast_root了！！！！
    }
#line 1333 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 6: /* CompileUnit: CompileUnit VarDecl  */
#line 119 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
        // 这里也不要改ast_root了！！
    }
#line 1342 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 7: /* CompileUnit: CompileUnit ConstDecl  */
#line 123 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                            {
        (yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
        // 这里也不要改ast_root了！
    }
#line 1351 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 8: /* FuncDef: BasicType T_ID T_L_PAREN T_R_PAREN Block  */
#line 132 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                                {
        type_attr funcReturnType = (yyvsp[-4].type);
        var_id_attr funcId = (yyvsp[-3].var_id);
		ast_node * formalParamsNode = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS);
        ast_node * blockNode = (yyvsp[0].node);
        (yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
    }
#line 1363 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 9: /* FuncDef: BasicType T_ID T_L_PAREN FormalParamList T_R_PAREN Block  */
#line 139 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                                               {
        type_attr funcReturnType = (yyvsp[-5].type);
        var_id_attr funcId = (yyvsp[-4].var_id);
        ast_node * formalParamsNode = (yyvsp[-2].node);
        ast_node * blockNode = (yyvsp[0].node);
        (yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
    }
#line 1375 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 10: /* FormalParamList: FormalParam  */
#line 149 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                  {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
    }
#line 1383 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 11: /* FormalParamList: FormalParamList T_COMMA FormalParam  */
#line 152 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                          {
        (yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
    }
#line 1391 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 12: /* FormalParam: BasicType T_ID  */
#line 158 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                     {
        // 普通变量形参
        ast_node * type_node = create_type_node((yyvsp[-1].type));
        ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});
        free((yyvsp[0].var_id).id);
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, id_node);
    }
#line 1403 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 13: /* FormalParam: BasicType T_ID FuncFParamArrayDim  */
#line 165 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                        {
        // 数组变量形参（可能多维）
        ast_node * type_node = create_type_node((yyvsp[-2].type));
        ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
        free((yyvsp[-1].var_id).id);
        ast_node * array_decl = create_contain_node(ast_operator_type::AST_OP_VAR_ARRAY_DECL, id_node, (yyvsp[0].node));
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, array_decl);
    }
#line 1416 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 14: /* FuncFParamArrayDim: T_L_SQUARE T_R_SQUARE  */
#line 176 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                            {
        // 第一个 [] 只是表示是数组，不建 dim
        (yyval.node) = nullptr;
    }
#line 1425 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 15: /* FuncFParamArrayDim: T_L_SQUARE ConstExp T_R_SQUARE  */
#line 180 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                     {
        // 第一个 [5] 建 dim
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIM, (yyvsp[-1].node));
    }
#line 1434 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 16: /* FuncFParamArrayDim: FuncFParamArrayDim T_L_SQUARE ConstExp T_R_SQUARE  */
#line 184 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                                        {
        if ((yyvsp[-3].node) == nullptr) {
            (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIM, (yyvsp[-1].node));
        } else {
            (yyval.node) = (yyvsp[-3].node)->insert_son_node(create_contain_node(ast_operator_type::AST_OP_ARRAY_DIM, (yyvsp[-1].node)));
        }
    }
#line 1446 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 17: /* Block: T_L_BRACE T_R_BRACE  */
#line 200 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                            {
		// 语句块没有语句

		// 为了方便创建一个空的Block节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK);
	}
#line 1457 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 18: /* Block: T_L_BRACE BlockItemList T_R_BRACE  */
#line 206 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                            {
		// 语句块含有语句

		// BlockItemList归约时内部创建Block节点，并把语句加入，这里不创建Block节点
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1468 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 19: /* BlockItemList: BlockItem  */
#line 217 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
		// 第一个左侧的孩子节点归约成Block节点，后续语句可持续作为孩子追加到Block节点中
		// 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node));
	}
#line 1478 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 20: /* BlockItemList: BlockItemList BlockItem  */
#line 222 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                  {
		// 把BlockItem归约的节点加入到BlockItemList的节点中
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1487 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 21: /* BlockItem: Statement  */
#line 232 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1495 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 22: /* BlockItem: VarDecl  */
#line 235 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_DECL_STMT, (yyvsp[0].node));
    }
#line 1503 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 23: /* BlockItem: ConstDecl  */
#line 238 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_DECL_STMT, (yyvsp[0].node));
    }
#line 1511 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 24: /* VarDecl: VarDeclExpr T_SEMICOLON  */
#line 249 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                  {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1519 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 25: /* VarDeclExpr: BasicType VarDef  */
#line 256 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                       {
        // 创建类型节点
        ast_node * type_node = create_type_node((yyvsp[-1].type));

        // 创建变量定义节点
        ast_node * decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
        decl_node->type = type_node->type;

        // 创建变量声明语句，并加入第一个变量
        (yyval.node) = create_var_decl_stmt_node(decl_node);
    }
#line 1535 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 26: /* VarDeclExpr: VarDeclExpr T_COMMA VarDef  */
#line 267 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                 {
        // 不要重新建type了！！！直接把VarDef挂到原来的VarDecl语句上
        (yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
    }
#line 1544 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 27: /* VarDef: T_ID  */
#line 276 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           {
        (yyval.node) = ast_node::New(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});
        free((yyvsp[0].var_id).id);
    }
#line 1553 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 28: /* VarDef: T_ID ArrayDim  */
#line 280 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                    {
        ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
        free((yyvsp[-1].var_id).id);
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_ARRAY_DECL, id_node, (yyvsp[0].node));
    }
#line 1563 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 29: /* VarDef: T_ID T_ASSIGN InitVal  */
#line 285 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                            {
        ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
        free((yyvsp[-2].var_id).id);
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, id_node, (yyvsp[0].node));
    }
#line 1573 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 30: /* VarDef: T_ID ArrayDim T_ASSIGN InitVal  */
#line 290 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                         {
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
		free((yyvsp[-3].var_id).id);

		ast_node * array_decl = create_contain_node(ast_operator_type::AST_OP_VAR_ARRAY_DECL, id_node, (yyvsp[-2].node));

		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, array_decl, (yyvsp[0].node));
	}
#line 1586 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 31: /* ArrayDim: T_L_SQUARE ConstExp T_R_SQUARE  */
#line 302 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIM, (yyvsp[-1].node));
    }
#line 1594 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 32: /* ArrayDim: ArrayDim T_L_SQUARE ConstExp T_R_SQUARE  */
#line 305 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                              {
        (yyval.node) = (yyvsp[-3].node)->insert_son_node(create_contain_node(ast_operator_type::AST_OP_ARRAY_DIM, (yyvsp[-1].node)));
    }
#line 1602 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 33: /* ConstExp: T_DIGIT  */
#line 311 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = ast_node::New((yyvsp[0].integer_num));
    }
#line 1610 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 34: /* ConstExp: AddExp  */
#line 314 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1618 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 35: /* InitVal: Expr  */
#line 323 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           {
        // 简单初始化
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_INITVAL, (yyvsp[0].node));
    }
#line 1627 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 36: /* InitVal: T_L_BRACE T_R_BRACE  */
#line 327 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        // 空初始化 {}
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_INITVAL);
    }
#line 1636 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 37: /* InitVal: T_L_BRACE InitValList T_R_BRACE  */
#line 331 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                      {
        // 多个初始化器 {initval, initval, ...}
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_INITVAL, (yyvsp[-1].node));
    }
#line 1645 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 38: /* InitValList: InitVal  */
#line 338 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_INITVAL, (yyvsp[0].node));
    }
#line 1653 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 39: /* InitValList: InitValList T_COMMA InitVal  */
#line 341 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                  {
        (yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
    }
#line 1661 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 40: /* ConstDecl: T_CONST BasicType ConstDefList T_SEMICOLON  */
#line 347 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                                 {
        ast_node * type_node = create_type_node((yyvsp[-2].type));
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONST_DECL, type_node, (yyvsp[-1].node));
    }
#line 1670 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 41: /* ConstDefList: ConstDef  */
#line 354 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
               {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1678 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 42: /* ConstDefList: ConstDefList T_COMMA ConstDef  */
#line 357 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                    {
        (yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
    }
#line 1686 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 43: /* ConstDef: T_ID T_ASSIGN ConstInitVal  */
#line 363 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                 {
        ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
        free((yyvsp[-2].var_id).id);
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, id_node, (yyvsp[0].node));
    }
#line 1696 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 44: /* ConstDef: T_ID ArrayDim T_ASSIGN ConstInitVal  */
#line 368 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                              {
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
		free((yyvsp[-3].var_id).id);

		ast_node * array_decl = create_contain_node(ast_operator_type::AST_OP_CONST_ARRAY_DECL, id_node, (yyvsp[-2].node));

		ast_node * array_init = create_contain_node(ast_operator_type::AST_OP_CONST_INITVAL, (yyvsp[0].node));

		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, array_decl, array_init);
	}
#line 1711 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 45: /* ConstInitVal: ConstExp  */
#line 381 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
               {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONST_INITVAL, (yyvsp[0].node));
    }
#line 1719 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 46: /* ConstInitVal: T_L_BRACE T_R_BRACE  */
#line 384 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONST_INITVAL);
    }
#line 1727 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 47: /* ConstInitVal: T_L_BRACE ConstInitValList T_R_BRACE  */
#line 387 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                           {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONST_INITVAL, (yyvsp[-1].node));
    }
#line 1735 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 48: /* ConstInitValList: ConstInitVal  */
#line 393 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                   {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONST_INITVAL, (yyvsp[0].node));
    }
#line 1743 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 49: /* ConstInitValList: ConstInitValList T_COMMA ConstInitVal  */
#line 396 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                            {
        (yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
    }
#line 1751 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 50: /* BasicType: T_INT  */
#line 406 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
            {
        (yyval.type) = (yyvsp[0].type);
    }
#line 1759 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 51: /* BasicType: T_FLOAT  */
#line 409 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.type) = (yyvsp[0].type);
    }
#line 1767 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 52: /* Statement: IFStmt  */
#line 420 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1775 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 53: /* Statement: T_RETURN Expr T_SEMICOLON  */
#line 423 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_RETURN, (yyvsp[-1].node));
    }
#line 1783 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 54: /* Statement: LVal T_ASSIGN Expr T_SEMICOLON  */
#line 426 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node));
    }
#line 1791 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 55: /* Statement: Block  */
#line 429 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
            {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1799 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 56: /* Statement: Expr T_SEMICOLON  */
#line 432 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                       {
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1807 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 57: /* Statement: T_SEMICOLON  */
#line 435 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                  {
        (yyval.node) = nullptr;
    }
#line 1815 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 58: /* Statement: T_WHILE T_L_PAREN Cond T_R_PAREN Statement  */
#line 438 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                                 {
        (yyval.node) = create_while_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1823 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 59: /* Statement: T_BREAK T_SEMICOLON  */
#line 441 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_break_node();
    }
#line 1831 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 60: /* Statement: T_CONTINUE T_SEMICOLON  */
#line 444 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                             {
        (yyval.node) = create_continue_node();
    }
#line 1839 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 61: /* IFStmt: T_IF T_L_PAREN Cond T_R_PAREN Statement  */
#line 451 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                              {
        (yyval.node) = create_if_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1847 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 62: /* IFStmt: T_IF T_L_PAREN Cond T_R_PAREN Statement T_ELSE IFStmt  */
#line 454 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                                            {
        (yyval.node) = create_if_else_node((yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1855 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 63: /* IFStmt: T_IF T_L_PAREN Cond T_R_PAREN Statement T_ELSE Statement  */
#line 457 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                                               {
        (yyval.node) = create_if_else_node((yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1863 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 64: /* Expr: T_DIGIT  */
#line 465 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = ast_node::New((yyvsp[0].integer_num));
    }
#line 1871 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 65: /* Expr: LOrExp  */
#line 468 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1879 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 66: /* AddExp: MulExp  */
#line 478 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1887 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 67: /* AddExp: MulExp AddOp MulExp  */
#line 481 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1895 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 68: /* AddExp: AddExp AddOp MulExp  */
#line 484 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1903 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 69: /* MulExp: UnaryExp  */
#line 493 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
               {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1911 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 70: /* MulExp: UnaryExp MulOp UnaryExp  */
#line 496 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                              {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1919 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 71: /* MulExp: MulExp MulOp UnaryExp  */
#line 499 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                            {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1927 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 72: /* RelExp: AddExp  */
#line 505 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1935 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 73: /* RelExp: AddExp RelOp AddExp  */
#line 508 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1943 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 74: /* RelExp: RelExp RelOp AddExp  */
#line 511 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1951 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 75: /* EqExp: RelExp  */
#line 517 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1959 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 76: /* EqExp: RelExp EqOp RelExp  */
#line 520 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1967 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 77: /* EqExp: EqExp EqOp RelExp  */
#line 523 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                        {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1975 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 78: /* LAndExp: EqExp  */
#line 529 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
            {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1983 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 79: /* LAndExp: LAndExp T_AND EqExp  */
#line 532 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_AND, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1991 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 80: /* LOrExp: LAndExp  */
#line 538 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1999 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 81: /* LOrExp: LOrExp T_OR LAndExp  */
#line 541 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_OR, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2007 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 82: /* AddOp: T_ADD  */
#line 547 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_ADD;
	}
#line 2015 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 83: /* AddOp: T_SUB  */
#line 550 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_SUB;
	}
#line 2023 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 84: /* MulOp: T_MUL  */
#line 556 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
            { (yyval.op_class) = (int)ast_operator_type::AST_OP_MUL; }
#line 2029 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 85: /* MulOp: T_DIV  */
#line 557 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
            { (yyval.op_class) = (int)ast_operator_type::AST_OP_DIV; }
#line 2035 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 86: /* MulOp: T_MOD  */
#line 558 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
            { (yyval.op_class) = (int)ast_operator_type::AST_OP_MOD; }
#line 2041 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 87: /* RelOp: T_LT  */
#line 562 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_class) = (int)ast_operator_type::AST_OP_LT; }
#line 2047 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 88: /* RelOp: T_LE  */
#line 563 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_class) = (int)ast_operator_type::AST_OP_LE; }
#line 2053 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 89: /* RelOp: T_GT  */
#line 564 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_class) = (int)ast_operator_type::AST_OP_GT; }
#line 2059 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 90: /* RelOp: T_GE  */
#line 565 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_class) = (int)ast_operator_type::AST_OP_GE; }
#line 2065 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 91: /* EqOp: T_EQ  */
#line 569 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_class) = (int)ast_operator_type::AST_OP_EQ; }
#line 2071 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 92: /* EqOp: T_NEQ  */
#line 570 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
            { (yyval.op_class) = (int)ast_operator_type::AST_OP_NEQ; }
#line 2077 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 93: /* Cond: LOrExp  */
#line 573 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2085 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 94: /* UnaryExp: PrimaryExp  */
#line 583 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                 {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2093 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 95: /* UnaryExp: T_SUB UnaryExp  */
#line 586 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_NEG, (yyvsp[0].node));
    }
#line 2101 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 96: /* UnaryExp: T_NOT UnaryExp  */
#line 589 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_NOT, (yyvsp[0].node));
    }
#line 2109 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 97: /* UnaryExp: T_ID T_L_PAREN T_R_PAREN  */
#line 592 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                               {
        // 注意这里即使没有实参也要建 real-params 黄框！
        ast_node * name_node = ast_node::New(std::string((yyvsp[-2].var_id).id), (yyvsp[-2].var_id).lineno);
        free((yyvsp[-2].var_id).id);
        ast_node * paramListNode = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS); // ✅注意
        (yyval.node) = create_func_call(name_node, paramListNode);
    }
#line 2121 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 98: /* UnaryExp: T_ID T_L_PAREN RealParamList T_R_PAREN  */
#line 599 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                             {
        ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);
        free((yyvsp[-3].var_id).id);
        ast_node * paramListNode = (yyvsp[-1].node);
        (yyval.node) = create_func_call(name_node, paramListNode);
    }
#line 2132 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 99: /* PrimaryExp: T_L_PAREN Expr T_R_PAREN  */
#line 610 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                       {
		// 带有括号的表达式
		(yyval.node) = (yyvsp[-1].node);
	}
#line 2141 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 100: /* PrimaryExp: T_DIGIT  */
#line 614 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                  {
        	// 无符号整型字面量

		// 创建一个无符号整型的终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].integer_num));
	}
#line 2152 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 101: /* PrimaryExp: LVal  */
#line 620 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                {
		// 具有左值的表达式

		// 直接传递到归约后的非终结符号PrimaryExp
		(yyval.node) = (yyvsp[0].node);
	}
#line 2163 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 102: /* PrimaryExp: T_FLOAT_LITERAL  */
#line 626 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                      {
        (yyval.node) = ast_node::New((yyvsp[0].float_num));
    }
#line 2171 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 103: /* RealParamList: Expr  */
#line 635 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                     {
		// 创建实参列表节点，并把当前的Expr节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
	}
#line 2180 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 104: /* RealParamList: RealParamList T_COMMA Expr  */
#line 639 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                     {
		// 左递归增加实参表达式
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 2189 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 105: /* LVal: T_ID  */
#line 647 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
           {
        (yyval.node) = ast_node::New((yyvsp[0].var_id));
        free((yyvsp[0].var_id).id);
    }
#line 2198 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 106: /* LVal: LVal T_L_SQUARE Expr T_R_SQUARE  */
#line 651 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"
                                      {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_ACCESS, (yyvsp[-3].node), (yyvsp[-1].node));
    }
#line 2206 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;


#line 2210 "/home/wcy/complier/npu_compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 657 "/home/wcy/complier/npu_compiler/frontend/flexbison/MiniC.y"

// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
